""" Problem 002 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms
"""

if __name__ == '__main__':
    i, j = 1, 1
    total = 0
    while i < 4_000_000:
        i, j = j, i
        i += j
        if i % 2 == 0:
            total += i
    print(total)
